### ISSUE TITLE
Import stops when 404

### ISSUE THREAD

**Issue by woolfg** [openpodcast/pipelines#28]
Importer stops when retrieving a 404 http status (e.g. spotify returns 404 if their data processor is delayed and there is no data yet)

```
 Starting Spotify connector
Launching connector.
Initializing environment
Done initializing environment
Traceback (most recent call last):
  File "/home/runner/work/pipelines/pipelines/spotify/main.py", line 305, in <module>
    main()
  File "/home/runner/work/pipelines/pipelines/spotify/main.py", line 190, in main
    fetch_and_capture(
  File "/home/runner/work/pipelines/pipelines/spotify/main.py", line 103, in fetch_and_capture
    raise e
  File "/home/runner/work/pipelines/pipelines/spotify/main.py", line 93, in fetch_and_capture
    data = connector_call()
  File "/home/runner/work/pipelines/pipelines/spotify/main.py", line 193, in <lambda>
    lambda: spotify_connector.listeners(start, end),
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/spotifyconnector/connector.py", line 322, in listeners
    return self._request(url, params=self._date_params(start, end))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/spotifyconnector/connector.py", line 221, in _request
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://generic.wg.spotify.com/podcasters/v0/shows/***/listeners?start=2023-01-13&end=2023-01-16
Error: Process completed with exit code 1.
```

**Comment by mre** [comment]
Fixed in `main`.
